

export const spacing = {
  
  xxs:   2,
  xs:    4,
  sm:    5,
  md:    8,
  lg:   10,
  xl:   12,
  '2xl': 14,
  '3xl': 15,
  '4xl': 16,
  '5xl': 20,
  '6xl': 25,
  '7xl': 30,

  
  screenPadding:      10,  
  screenPaddingTop:   17,  
  sectionPaddingH:    20,  
  cardPadding:        14,  
  cardPaddingTop:     10, 
  cardPaddingInfo:    10,  
  cardMargin:          5,  
  cardSpacing:        14,  
  inputPaddingH:      10,  
  inputMarginLeft:    25,  
  inputMarginBottom:  20,  
  buttonPaddingV:      8,  
  buttonPaddingLeft: 120,  
  iconMarginRight:    20,  
  iconPadding:        10,  
  authTitleLeft:      32,  
  authTitleTop:       63,  
  paymentPadding:     16, 
  couponPaddingLeft:  20,  
  couponGap:          15,  
  qtyBtnPaddingH:      8,  
  qtyBtnPaddingV:      2,  
  tabBarPaddingBottom: 5,  
};
